/**
 * OIKONO Frontend Configuration
 * Deployed on Somnia Testnet - 2026-06-01
 */

const CONFIG = {
    CHAIN_ID: '0xC488',
    RPC_URL: 'https://dream-rpc.somnia.network',
    WS_URL: 'wss://dream-rpc.somnia.network/ws',

    CONTRACTS: {
        // Agent Intelligence
        OikonoAgent: '0x8292B838ce0C0eB2303e4eE3e8dc256eD8d39E74',
        AgentRuntime: '0x42D284771C77bBAbC487a029e081b5504bCA41CA',
        AgentMemory: '0x9798995ad174dc01Bd1C6f7177e7EE220937b098',
        GameKnowledgeBase: '0x2038D5f321Cd8A9eC2cAbf9CC61Ce77d982585C6',
        AgentRegistry: '0x9E3eB05a2131472F457Ab951D404Aa737E4e6FeC',
        AgentVault: '0x232A33D72A88836db88DEE4b8f06e379eBC43f7a',

        // Game Registry
        GameRegistry: '0xDcDD689932DD7026C1cDC723F6E49A17953b332f',

        // Metrics & Analysis
        MetricsRegistry: '0xd43e055198f9eeca623249CB7115Ba90537AE6C5',
        PatternDetector: '0x3288A2545Df449E1565506a059635b920dfa2E57',
        SuggestionEngine: '0x261857a7aC8cB48A40069863774b7ff99EEBF0a2',
        GameTypeManager: '0x20c3dc3eA21bdd79C087775dD23b38290962C7B6',

        // LLM Integration
        LLMInvoker: '0xdA11A6Cc18bA511F0265283d5082adf85C20e69D',

        // Plugins
        SpawnPlugin: '0x1362B3a42B7d1d1382f02b597b4f1aeB992547f0',
        EconomyPlugin: '0x24D14B259Ac93283e29d4E3536c7fe03aaA0Ae12',
        NarrativePlugin: '0xdAAbc5d9Bb026F83D54E9E08F235205a7e5331C1',
        BalancePlugin: '0xC8341A97371Cf58B3e57f815B392c9267F7e7C85',

        // Game
        PlayerRegistry: '0x11ec0E392b455212347D44b3B383C7D6B71571bB',
        GameMaster: '0x2A59DE2fe88C0cDB36687f0C8056f132D0FE5c42',
        EnemyNFT: '0xdC42BEe9FcFB056eaB5A6654Bd86B3FD8aEdeEdf',
        BattleArena: '0x3b4D12cCcb9d72Ae40551bc3A3f0eb93ae916683',
        RewardDistributor: '0xD151BFc16B340E98A56E03B0663Bda6904F24996',

        // Economy
        OIKToken: '0x265661d7D4df3bdE1F374086CA5e2D23cf37Beb9',
        EconomyParams: '0xca43CAaaBAF7167A204eb8E97b60a7B93baBE2d5',
        Treasury: '0x1cD055B1159bD6C4d1098e5Bb7b70c44aA0aeF3c',

        // Utils
        CircuitBreaker: '0xa4176d4Eeee28fa3a3c0efA2678Fbaff053975aD',
        AntiSybil: '0x6ed39eF55C2408749a2b11ECE8a87D993332C4C4',
    },

    ABI: {
        GameRegistry: [
            'function registerGame(string name, string gameType, string description, address gameAddress, string metadata, tuple(bool canSpawn, bool canAdjustEconomy, bool canGenerateNarrative, bool canAdjustDifficulty, uint256 maxChangePerEpoch, uint256 epochLength) config) external returns (uint256)',
            'function addContract(uint256 gameId, address contractAddress, string role, bytes32[] eventHashes) external',
            'function getGame(uint256 gameId) external view returns (address owner, string name, string gameType, string description, string metadata, bool isActive, bool isVerified, uint256 totalEvents, uint256 totalActions)',
            'function getGameContracts(uint256 gameId) external view returns (address[] addresses, string[] roles, bool[] active)',
            'function getGamesByOwner(address owner) external view returns (uint256[])',
            'function deactivateGame(uint256 gameId) external',
            'function activateGame(uint256 gameId) external',
            'event GameRegistered(uint256 indexed gameId, address indexed owner, string name, string gameType)',
        ],
        MetricsRegistry: [
            'function defineMetric(uint256 gameId, string name, string dataType, string source, uint256 healthyMin, uint256 healthyMax, bool isHigherBetter) external',
            'function recordMetric(uint256 gameId, string name, uint256 value) external',
            'function getLatest(uint256 gameId, string name) external view returns (uint256)',
            'function getStats(uint256 gameId, string name) external view returns (uint256 latest, uint256 min, uint256 max, uint256 avg, uint256 count, uint256 lastUpdated)',
            'function getMetricNames(uint256 gameId) external view returns (string[] memory)',
            'function isHealthy(uint256 gameId, string name) external view returns (bool)',
            'function getChange(uint256 gameId, string name) external view returns (int256)',
            'event MetricDefined(uint256 indexed gameId, string metricName, string dataType, string source)',
            'event MetricRecorded(uint256 indexed gameId, string metricName, uint256 value, uint256 timestamp)',
        ],
        PatternDetector: [
            'function addRule(uint256 gameId, string ruleType, string metricName, uint256 threshold, uint256 period) external',
            'function addDefaultRules(uint256 gameId, string gameType) external',
            'function detectPatterns(uint256 gameId) external',
            'function getActivePatterns(uint256 gameId) external view returns (tuple(uint256 patternId, uint256 gameId, string patternType, string metricName, string metricName2, string description, uint256 severity, uint256 confidence, uint256 detectedAt, bool isActive, bytes data)[] memory)',
            'function getPatternCount(uint256 gameId) external view returns (uint256)',
            'event PatternDetected(uint256 indexed gameId, uint256 indexed patternId, string patternType, string description, uint256 severity)',
        ],
        SuggestionEngine: [
            'function generateSuggestions(uint256 gameId) external',
            'function markImplemented(uint256 gameId, uint256 suggestionId) external',
            'function getActiveSuggestions(uint256 gameId) external view returns (tuple(uint256 suggestionId, uint256 gameId, uint256 patternId, string category, string priority, string description, string action, uint256 confidence, uint256 expectedImpact, bool implemented, uint256 implementedAt, bytes outcomeData)[] memory)',
            'function getSuggestionCount(uint256 gameId) external view returns (uint256)',
            'event SuggestionCreated(uint256 indexed gameId, uint256 indexed suggestionId, string category, string priority, string description)',
        ],
        GameTypeManager: [
            'function applyTemplate(uint256 gameId, string typeName) external',
            'function getRegisteredTypes() external view returns (string[] memory)',
            'function getConfig(string typeName) external view returns (string description, uint256 metricCount, uint256 ruleCount)',
        ],
        OikonoAgent: [
            'function requestAction(uint256 gameId, string actionType, bytes gameData) external returns (uint256 decisionId)',
            'function reportOutcome(uint256 decisionId, bool success, bytes resultData) external',
            'function getStats() external view returns (uint256 decisions, uint256 llmCalls, uint256 autoActions)',
        ],
        AgentMemory: [
            'function getGameStats(address game) external view returns (uint256 totalDecisions, uint256 successfulDecisions, uint256 failedDecisions, uint256 successRate)',
            'function getPatterns(address game) external view returns (string[] patternTypes, uint256[] confidences, uint256[] occurrences)',
        ],
        PlayerRegistry: [
            'function getPlayer(address player) external view returns (uint256 x, uint256 y, uint256 xp, uint256 level, uint256 totalBattles, uint256 wins, uint256 losses, bool exists)',
            'function playerExists(address player) external view returns (bool)',
            'function registerPlayer(uint256 x, uint256 y) external',
            'function move(uint256 x, uint256 y) external',
            'function getAllPlayers() external view returns (address[] memory)',
            'function totalPlayers() external view returns (uint256)',
            'event PlayerRegistered(address indexed player, uint256 x, uint256 y)',
            'event PlayerMoved(address indexed player, uint256 x, uint256 y, uint256 xp, uint256 level)',
            'event PlayerLevelUp(address indexed player, uint256 newLevel)',
            'event PlayerBattleResult(address indexed player, bool won, uint256 xpGained)',
        ],
        EnemyNFT: [
            'function mintFromAI(address player, string name, string enemyClass, string element, uint256 power, uint256 threatLevel, string metadataURI) external returns (uint256)',
            'function ownerOf(uint256 tokenId) external view returns (address)',
            'function tokenURI(uint256 tokenId) external view returns (string memory)',
            'function getEnemy(uint256 tokenId) external view returns (string name, string enemyClass, string element, uint256 power, uint256 threatLevel, address creator, uint256 battlesWon, uint256 battlesLost, bool isBoss)',
            'function getPlayerEnemies(address player) external view returns (uint256[] memory)',
            'function totalEnemiesMinted() external view returns (uint256)',
            'function setMinter(address minter) external',
            'event EnemyMinted(uint256 indexed tokenId, address indexed creator, string name, string enemyClass, uint256 power)',
            'event EnemyDefeated(uint256 indexed tokenId, address indexed by)',
        ],
        BattleArena: [
            'function executeBattle(uint256 enemyTokenId) external',
            'function claimRewards() external',
            'function getPendingRewards(address player) external view returns (uint256)',
            'function getBattleHistory(uint256 count) external view returns (tuple(address player, uint256 enemyTokenId, bool playerWon, uint256 xpGained, uint256 rewardAmount, uint256 timestamp)[] memory)',
            'function getPlayerBattleHistory(address player) external view returns (tuple(address player, uint256 enemyTokenId, bool playerWon, uint256 xpGained, uint256 rewardAmount, uint256 timestamp)[] memory)',
            'function totalBattles() external view returns (uint256)',
            'function baseReward() external view returns (uint256)',
            'function baseEntryFee() external view returns (uint256)',
            'event BattleStarted(address indexed player, uint256 enemyTokenId, uint256 entryFee)',
            'event BattleEnded(address indexed player, uint256 enemyTokenId, bool playerWon, uint256 reward, uint256 xpGained)',
            'event RewardClaimed(address indexed player, uint256 amount)',
        ],
        OIKToken: [
            'function balanceOf(address account) external view returns (uint256)',
            'function transfer(address to, uint256 amount) external returns (bool)',
            'function approve(address spender, uint256 amount) external returns (bool)',
            'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
            'function totalSupply() external view returns (uint256)',
            'function totalBurned() external view returns (uint256)',
            'function transfersEnabled() external view returns (bool)',
            'function enableTransfers() external',
            'function mint(address to, uint256 amount) external',
            'function burn(uint256 amount) external',
            'function canClaimDailyRewards(address account) external view returns (bool)',
            'function MAX_SUPPLY() external view returns (uint256)',
            'function name() external view returns (string memory)',
            'function symbol() external view returns (string memory)',
            'function decimals() external view returns (uint8)',
        ],
        Treasury: [
            'function burnTokens(string category, uint256 amount) external',
            'function executeBuyback(uint256 amount) external',
            'function getStats() external view returns (uint256 totalBurned, uint256 totalBuyback, uint256 balance)',
            'function receiveTokens(string category) external',
            'function calculateBurnAmount(uint256 baseAmount, uint256 category) external view returns (uint256)',
            'function totalBurned() external view returns (uint256)',
            'function totalBuybackAmount() external view returns (uint256)',
            'function lastBuybackTime() external view returns (uint256)',
            'event TokensBurned(string category, uint256 amount)',
            'event BuybackExecuted(uint256 amount, uint256 timestamp)',
        ],
        RewardDistributor: [
            'function distributeBattleReward(address player, uint256 enemyPower) external returns (uint256)',
            'function distributeQuestReward(address player, uint256 questDifficulty) external returns (uint256)',
            'function calculateReward(uint256 baseReward, uint256 enemyPower) external view returns (uint256)',
            'function getStats() external view returns (uint256 totalDistributed, uint256 emissionRate, uint256 currentPhase, uint256 remainingTime)',
            'function getCurrentEmission() external view returns (uint256)',
            'function totalDistributed() external view returns (uint256)',
            'function currentEmissionRate() external view returns (uint256)',
            'function emissionPhase() external view returns (uint256)',
            'event RewardDistributed(address indexed player, uint256 amount, string category)',
            'event EmissionPhaseChanged(uint256 newPhase, uint256 newRate)',
        ],
        AntiSybil: [
            'function canMove(address player) external view returns (bool)',
            'function canBattle(address player) external view returns (bool)',
            'function canTransferReward(address player) external view returns (bool)',
            'function hasMinimumStake(address player) external view returns (bool)',
            'function hasMetUniqueOpponentRequirement(address player) external view returns (bool)',
            'function recordMove(address player) external',
            'function recordBattle(address player, address opponent) external',
            'function recordStake(address player, uint256 amount) external',
            'function recordUnstake(address player, uint256 amount) external',
            'function stakedAmount(address player) external view returns (uint256)',
            'function lastMoveTime(address player) external view returns (uint256)',
            'function lastBattleTime(address player) external view returns (uint256)',
            'function MOVE_COOLDOWN() external view returns (uint256)',
            'function BATTLE_COOLDOWN() external view returns (uint256)',
            'function MIN_STAKE() external view returns (uint256)',
            'event CooldownTriggered(address indexed player, string action, uint256 cooldownEnd)',
            'event Staked(address indexed player, uint256 amount)',
        ],
        CircuitBreaker: [
            'function paused() external view returns (bool)',
            'function voteToPause() external',
            'function emergencyPause() external',
            'function unpause() external',
            'function forceUnpause() external',
            'function addGuardian(address guardian) external',
            'function removeGuardian(address guardian) external',
            'function getGuardians() external view returns (address[] memory)',
            'function getGuardianCount() external view returns (uint256)',
            'function getCurrentVotes() external view returns (uint256)',
            'function guardians(address guardian) external view returns (bool)',
            'function requiredGuardianVotes() external view returns (uint256)',
            'event Paused(address indexed by)',
            'event Unpaused(address indexed by)',
            'event GuardianAdded(address indexed guardian)',
            'event GuardianRemoved(address indexed guardian)',
        ],
        GameTypeTemplates: [
            'function applyTemplate(uint256 gameId, string typeName) external',
            'function getRegisteredTypes() external view returns (string[] memory)',
            'function getConfig(string typeName) external view returns (string description, uint256 metricCount, uint256 ruleCount)',
            'function getMetricTemplates(string typeName) external view returns (tuple(string name, string dataType, string source, uint256 healthyMin, uint256 healthyMax, bool isHigherBetter)[] memory)',
            'function getRuleTemplates(string typeName) external view returns (tuple(string ruleType, string metricName, uint256 threshold, uint256 period)[] memory)',
            'event GameTypeRegistered(string typeName, string description)',
        ],
        AgentRuntime: [
            'function registerGame(string name, address pluginAddress) external',
            'function autoRegisterGame(address gameAddress) external',
            'function getGame(address gameAddress) external view returns (string name, address plugin, bool isActive, uint256 totalExecutions)',
            'function getRequest(uint256 requestId) external view returns (address requester, uint8 actionType, uint8 status, uint256 timestamp)',
            'function getStats() external view returns (uint256 total, uint256 successful, uint256 failed, uint256 llmCalls)',
            'function getAllGames() external view returns (address[] memory)',
            'function subscribeToEvent(bytes32 eventSignature, uint256 deposit) external payable',
            'function setLLMMode(bool useLLM) external',
            'function toggleGameActive(address gameAddress) external',
            'event GameRegistered(address indexed game, string name, address plugin)',
            'event ActionCompleted(uint256 indexed requestId, bool success, uint256 executionTime)',
        ],
        LLMInvoker: [
            'function invokeLLM(address game, string decisionType, bytes contextData, bytes gameState) external payable returns (uint256 requestId)',
            'function requests(uint256 requestId) external view returns (uint256 requestId_, address game, string decisionType, bytes contextData, uint256 timestamp, bool processed)',
            'function getStats() external view returns (uint256 totalDecisions, uint256 llmCalls, uint256 autoActions)',
            'event LLMRequestSent(uint256 indexed requestId, address indexed game, string decisionType, string promptSummary)',
            'event LLMResponseReceived(uint256 indexed requestId, address indexed game, string action, bool success)',
        ],
        SpawnPlugin: [
            'function configureGame(address game, string entityType, string[12] namePool, uint256 minPower, uint256 maxPower, string[6] attributePool, bool scaleWithPlayer, uint256 baseScaleRate) external',
            'function quickConfigure(address game, string gameType) external',
            'function getEntity(uint256 entityId) external view returns (address game, address spawner, string entityType, string name, string attribute, uint256 power, uint256 timestamp)',
            'function getGameStats(address game) external view returns (uint256 total)',
            'function totalSpawned() external view returns (uint256)',
            'function gameConfigs(address game) external view returns (string entityType, uint256 minPower, uint256 maxPower, bool scaleWithPlayer, uint256 baseScaleRate)',
            'event EntitySpawned(uint256 indexed entityId, address indexed game, address indexed spawner, string name, uint256 power)',
            'event ConfigUpdated(address indexed game, string entityType)',
        ],
        EconomyPlugin: [
            'function configureGame(address token, address treasury, uint256 epochLength, uint256 targetWinRate) external',
            'function getParams(address game) external view returns (int256 rewardMult, int256 burnRate, int256 mintCostMult, int256 difficultyScale, int256 entryFeeMult)',
            'function getEpochCount(address game) external view returns (uint256)',
            'function gameConfigs(address game) external view returns (address token, address treasury, uint256 epochLength, uint256 targetWinRate, uint256 targetVelocity, uint256 minSupplyRatio, uint256 maxSupplyRatio)',
            'event EconomyConfigured(address indexed game, address token)',
            'event ParamsAdjusted(address indexed game, int256 rewardMult, int256 burnRate, int256 mintCostMult)',
            'event EpochRecorded(address indexed game, uint256 epoch, uint256 winRate)',
        ],
        NarrativePlugin: [
            'function generateDialogue(uint256 questId, string npcName, string context) external view returns (tuple(string speaker, string text, string emotion)[] memory)',
            'function getQuest(uint256 questId) external view returns (address game, address player, uint8 questType, string title, uint256 targetCount, uint256 currentProgress, uint256 reward, uint256 difficulty, bool isActive)',
            'function getPlayerQuests(address player) external view returns (uint256[] memory)',
            'function updateProgress(uint256 questId, uint256 progress) external',
            'function setThemes(string[] themes) external',
            'function nextQuestId() external view returns (uint256)',
            'event QuestGenerated(uint256 indexed questId, address indexed game, address indexed player, uint8 questType, string title, uint256 reward)',
            'event QuestProgressed(uint256 indexed questId, uint256 progress)',
            'event QuestCompleted(uint256 indexed questId, uint256 reward)',
        ],
        BalancePlugin: [
            'function configureGame(uint256 targetWinRate, uint256 difficultyFloor, uint256 difficultyCeiling) external',
            'function getDifficulty(address game) external view returns (uint256)',
            'function getMetrics(address game) external view returns (uint256 totalBattles, uint256 totalWins, uint256 winRate, uint256 avgCompletionTime, uint256 playerCount)',
            'function calculatePlayerDifficulty(address game, uint256 playerLevel, uint256 zone) external view returns (uint256)',
            'function updateDifficultyCurve(uint256 baseDifficulty, uint256 scalingFactor, bool adaptiveScaling) external',
            'function gameConfigs(address game) external view returns (uint256 targetWinRate, uint256 targetCompletionTime, uint256 difficultyFloor, uint256 difficultyCeiling, uint256 adjustmentInterval)',
            'event BalanceConfigured(address indexed game, uint256 targetWinRate)',
            'event DifficultyAdjusted(address indexed game, uint256 oldDifficulty, uint256 newDifficulty, string reason)',
            'event MetricsRecorded(address indexed game, uint256 winRate, uint256 playerCount)',
        ],
        GameMaster: [
            'function subscribeToPlayerMoved(bytes32 eventSig) external payable',
            'function triggerEnemyGeneration(address player) external',
            'function getStats() external view returns (uint256 totalEnemies, uint256 totalLLM, uint256 subscriptions)',
            'function setLLMMode(bool useLLM) external',
            'function setMinter(address minter) external',
            'function playerRegistry() external view returns (address)',
            'function enemyNFT() external view returns (address)',
            'function useLLMAgent() external view returns (bool)',
            'function totalEnemiesGenerated() external view returns (uint256)',
            'function totalLLMCalls() external view returns (uint256)',
            'function totalSubscriptions() external view returns (uint256)',
            'function pendingRequests(uint256 requestId) external view returns (address player, uint256 x, uint256 y, uint256 xp, uint256 level, bool processed)',
            'event EnemyGenerated(address indexed player, uint256 indexed tokenId, string name, string enemyClass, uint256 power)',
            'event LLMRequestSent(uint256 indexed requestId, address indexed player, string prompt)',
            'event LLMResponseReceived(uint256 indexed requestId, string enemyData)',
            'event SubscriptionCreated(bytes32 eventSig, address emitter, address handler)',
        ],
    },

    GAME_TYPE_TEMPLATES: {
        rpg: {
            name: 'RPG',
            description: 'Role-Playing Games',
            metrics: [
                { name: 'win_rate', healthy: '45-65%', description: 'Player win rate' },
                { name: 'token_velocity', healthy: '5-20', description: 'Token circulation speed' },
                { name: 'gold_inflation', healthy: '0-5%/day', description: 'Gold inflation rate' },
                { name: 'retention_d7', healthy: '20-40%', description: '7-day retention' },
                { name: 'avg_session_length', healthy: '15-60 min', description: 'Session duration' },
            ],
            rules: [
                { type: 'spike', metric: 'win_rate', threshold: '20%', description: 'Win rate spike' },
                { type: 'drop', metric: 'retention_d7', threshold: '15%', description: 'Retention drop' },
            ]
        },
        card: {
            name: 'Card Game',
            description: 'Card Games (TCG/CCG)',
            metrics: [
                { name: 'pack_ev', healthy: '0.9-1.1', description: 'Pack expected value' },
                { name: 'meta_diversity', healthy: '>65%', description: 'Meta diversity index' },
                { name: 'collection_rate', healthy: '30-50%', description: 'Collection progress' },
            ],
            rules: [
                { type: 'drop', metric: 'pack_ev', threshold: '20%', description: 'Pack EV dropped' },
            ]
        },
        pvp: {
            name: 'PvP',
            description: 'PvP Games',
            metrics: [
                { name: 'queue_time', healthy: '<30 sec', description: 'Queue wait time' },
                { name: 'match_balance', healthy: '<200', description: 'ELO difference' },
            ],
            rules: [
                { type: 'trend_up', metric: 'queue_time', threshold: '50% over 7d', description: 'Queue time increasing' },
            ]
        },
    },

    CONTRACT_ROLES: {
        token: { label: 'Token', description: 'Game token contract' },
        nft: { label: 'NFT', description: 'NFT collection contract' },
        marketplace: { label: 'Marketplace', description: 'Trading marketplace' },
        staking: { label: 'Staking', description: 'Staking/yield contract' },
        game_logic: { label: 'Game Logic', description: 'Core game mechanics' },
    },
};
