// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title EnemyNFT
 * @notice Dynamic ERC-721 NFT for AI-generated enemies in OIKONO
 * @dev Metadata stored on-chain, generated by Somnia LLM Inference
 */
contract EnemyNFT is ERC721, ERC721URIStorage, Ownable {
    uint256 public nextTokenId;

    // Enemy attributes stored on-chain
    struct EnemyData {
        string name;
        string enemyClass;    // assassin, tank, mage, berserker, healer, ranger
        string element;       // fire, ice, shadow, lightning, void, earth
        uint256 power;        // 40-100
        uint256 threatLevel;  // 1-10
        address creator;      // Player who triggered generation
        uint256 createdAt;
        uint256 battlesWon;
        uint256 battlesLost;
        bool isBoss;
    }

    mapping(uint256 => EnemyData) public enemies;
    mapping(address => uint256[]) public playerEnemies;

    // ERC-721 URIStorage override markers
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    event EnemyMinted(
        uint256 indexed tokenId,
        address indexed creator,
        string name,
        string enemyClass,
        uint256 power
    );
    event EnemyDefeated(uint256 indexed tokenId, address indexed by);
    event EnemyBattleResult(uint256 indexed tokenId, bool won);
    event MinterSet(address indexed minter);

    address public minter;

    constructor(
        address initialOwner
    ) ERC721("OIKONO Enemy", "OIKENEMY") Ownable(initialOwner) {}

    /**
     * @notice Set authorized minter (GameMaster)
     */
    function setMinter(address _minter) external onlyOwner {
        minter = _minter;
        emit MinterSet(_minter);
    }

    /**
     * @notice Mint a new enemy NFT (only called by GameMaster/minter)
     */
    function mintFromAI(
        address player,
        string memory name,
        string memory enemyClass,
        string memory element,
        uint256 power,
        uint256 threatLevel,
        string memory metadataURI
    ) external returns (uint256) {
        require(
            msg.sender == minter || msg.sender == owner(),
            "Not authorized"
        );
        require(power >= 40 && power <= 100, "Power must be 40-100");
        require(threatLevel >= 1 && threatLevel <= 10, "Threat must be 1-10");

        uint256 tokenId = nextTokenId++;

        enemies[tokenId] = EnemyData({
            name: name,
            enemyClass: enemyClass,
            element: element,
            power: power,
            threatLevel: threatLevel,
            creator: player,
            createdAt: block.timestamp,
            battlesWon: 0,
            battlesLost: 0,
            isBoss: power >= 90
        });

        _safeMint(player, tokenId);
        _setTokenURI(tokenId, metadataURI);

        playerEnemies[player].push(tokenId);

        emit EnemyMinted(tokenId, player, name, enemyClass, power);

        return tokenId;
    }

    /**
     * @notice Record battle result
     */
    function recordBattleResult(uint256 tokenId, bool playerWon) external onlyOwner {
        EnemyData storage enemy = enemies[tokenId];
        if (playerWon) {
            enemy.battlesLost++;
            emit EnemyDefeated(tokenId, msg.sender);
        } else {
            enemy.battlesWon++;
        }
        emit EnemyBattleResult(tokenId, playerWon);
    }

    /**
     * @notice Get enemy data
     */
    function getEnemy(uint256 tokenId) external view returns (
        string memory name,
        string memory enemyClass,
        string memory element,
        uint256 power,
        uint256 threatLevel,
        address creator,
        uint256 battlesWon,
        uint256 battlesLost,
        bool isBoss
    ) {
        EnemyData memory enemy = enemies[tokenId];
        return (
            enemy.name,
            enemy.enemyClass,
            enemy.element,
            enemy.power,
            enemy.threatLevel,
            enemy.creator,
            enemy.battlesWon,
            enemy.battlesLost,
            enemy.isBoss
        );
    }

    /**
     * @notice Get all enemy IDs owned by a player
     */
    function getPlayerEnemies(address player) external view returns (uint256[] memory) {
        return playerEnemies[player];
    }

    /**
     * @notice Get total enemies minted
     */
    function totalEnemiesMinted() external view returns (uint256) {
        return nextTokenId;
    }
}
